### ISSUE TITLE
App fails to launch from My People when in a terminated state

### ISSUE THREAD

**Issue by mchipeta** [tonyPendolino/MyPeopleBuild2017#1]
Hi,

Thanks for the very insightful [presentation](https://channel9.msdn.com/Events/Build/2017/P4056) on Channel 9.

I've been integrating an app with My People, but I've encountered a problem which I've managed to reproduce in your sample. If I click on 'Launch Full App' while the app is in a terminated state, it doesn't launch. However, Skype, Mail and People seem to launch without any issues. 

Do you have any ideas on how to overcome this problem?

Kind regards,
Malumbo

**Comment by cbarkerms** [comment]
thank you for flagging.  we were not launching via the UI thread.  I just pushed up the fix to master so please pull the latest.

**Comment by mchipeta** [comment]
Thank you. It now works as expected.
